// 자료 탭 세부 페이지 콘텐츠 (수정방안 §18~53).
// 지금은 코드에 시드. 관리자 인라인 편집(§16)은 콘텐츠 테이블이 생기면 이 구조를 그대로 옮긴다.
// officialLocation 미지정 시 "강원대학교 연구실안전관리시스템"으로 표시.

const SYS = '강원대학교 연구실안전관리시스템'

export const RESOURCE_CATEGORIES = [
  { key: 'notice', label: '공지사항' }, // 게시판(별도 처리)
  { key: 'waste', label: '폐기물' },
  { key: 'special', label: '특별관리물질' },
  { key: 'prior', label: '사전유해인자' },
  { key: 'signage', label: '안전표지·보호구' },
  { key: 'ops', label: '연구실 운영' },
]

export const RESOURCE_GUIDES = {
  waste: {
    label: '폐기물',
    sections: [
      {
        key: 'flow', label: '처리 절차', title: '폐기물 처리 절차',
        summary: '연구실에서 나온 화학 폐기물은 성상을 먼저 확인하고, 알맞은 용기·스티커·양식을 갖춘 뒤 지정 장소·절차에 따라 배출합니다.',
        audience: '폐기물을 배출하는 연구활동종사자', timing: '폐기물 발생 시마다 · 지정 수거일 전',
        steps: ['폐기물 발생', '폐액 / 고상 / 폐시약 구분', '성상 확인', '적합한 용기·스티커·양식 준비', '지정 장소·절차에 따라 배출'],
        notice: '앱은 처리 완료를 기록하지 않습니다. 실제 배출·처리는 학교 절차를 따릅니다.',
        actions: [],
      },
      {
        key: 'reagent', label: '폐시약', title: '폐시약(불용 시약) 처리',
        summary: '더 이상 쓰지 않는 시약을 아래에서 검색·선택해 학교 처리에 필요한 정보(잔량·위치·Lot 등)를 모읍니다. 실제 폐기 처리와 요청은 앱에서 하지 않습니다.',
        audience: '연구활동종사자 · 연구실책임자', timing: '불용 시약 확인 시 · 정기 정리 시',
        roles: ['worker', 'manager', 'director'],
        steps: ['폐시약 검색·선택', '시약 정보(잔량·위치·Lot) 확인', '작성 참고용 Excel 내보내기', '학교 절차에 따라 처리 의뢰'],
        notice: '중복 재고 데이터를 새로 만들지 않고 현재 보유 중(active)인 Lot 정보를 그대로 사용합니다. 폐기 요청/상태는 여기서 만들지 않습니다. 내보내는 Excel은 작성 참고용입니다(학교 공식 양식이 확인되지 않음).',
        embed: 'wasteReagent',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'liquid', label: '폐액', title: '폐액 처리',
        summary: '폐액은 성상을 확인해 유기/무기/산성/알칼리로 구분하고, 학교 지정 폐수용기에 전표·스티커를 갖춰 과충전 없이 밀폐해 배출합니다.',
        audience: '폐액을 배출하는 연구활동종사자', timing: '폐액 발생 시 · 용기 70~80% 차기 전',
        steps: ['폐액 성상 확인', '유기 / 무기 / 산성 / 알칼리 구분', '학교 지정 폐수용기 사용', '전표·성상별 스티커 확인', '과충전하지 않고 밀폐', '보호구 착용', '지정 장소로 운반'],
        notice: '서로 다른 화학물질 조합에 대해 앱이 "혼합 가능 / 안전"을 자동 판정하지 않습니다. 혼재금지 자료를 직접 확인하세요.',
        actions: [
          { key: 'mix-forbid', label: '혼재금지 확인' },
          { key: 'check-form', label: '폐기 전 성상 확인' },
          { key: 'pickup', label: '수거장소 확인' },
        ],
      },
      {
        key: 'solid', label: '고상폐기물', title: '고상폐기물 처리',
        summary: '오염된 장갑·초자류 등 고상폐기물은 스티커를 부착하고 처리의뢰서를 작성해 지정 절차로 배출합니다.',
        audience: '연구활동종사자', timing: '고상폐기물 발생 시',
        steps: ['고상폐기물 분리', '스티커 부착', '처리의뢰서 작성', '지정 장소로 배출'],
        notice: '별도의 고상폐기물 DB는 만들지 않습니다. 공식 양식 다운로드와 절차 안내에 집중합니다.',
        actions: [],
      },
      {
        key: 'mix-forbid', label: '혼재금지', title: '혼재금지 화학물질',
        summary: '함께 보관·배출하면 위험한 화학물질 조합을 확인합니다. 공식 혼재금지 자료를 기준으로 판단합니다.',
        audience: '시약을 보관·폐기하는 모든 연구활동종사자', timing: '보관 위치 변경 시 · 폐액 배출 시',
        steps: ['배출/보관하려는 물질 확인', '혼재금지 자료에서 조합 확인', '분리 보관 · 분리 배출'],
        notice: '앱은 임의 조합의 안전 여부를 자동 판정하지 않습니다.',
        actions: [],
      },
      {
        key: 'characterize', label: '성상 확인', title: '폐기 전 성상 확인',
        summary: '폐기물의 물리·화학적 성상(pH, 인화성, 유해성 등)을 배출 전에 확인합니다.',
        audience: '폐기물 배출자', timing: '용기 라벨링 · 배출 직전',
        steps: ['MSDS/GHS로 유해·위험성 확인', 'pH·인화성 등 성상 구분', '성상별 스티커·전표 작성'],
        notice: '',
        actions: [{ key: 'reagent-lookup', label: '시약 정보 조회' }],
      },
      {
        key: 'pickup', label: '수거장소·경로', title: '수거 장소 및 경로',
        summary: '지정(실험·의료)폐기물의 수거 장소와 이동 경로 안내입니다.',
        audience: '폐기물 운반자', timing: '수거일 · 배출일',
        steps: ['현재 사용 자료의 개정일/연도 확인', '지정 수거 장소로 경로에 따라 운반'],
        notice: '수거 장소 및 일정은 변경될 수 있습니다. 현재 사용 자료의 개정일/연도를 확인하세요.',
        actions: [],
      },
      {
        key: 'classify', label: '성상별 분류', title: '연구실 내 화학약품 성상별 분류 방법',
        summary: '화학약품을 성상(위험물 유별 등)별로 분류·보관하는 기준입니다. 시약 목록의 "위험물유별" 필터와 연계됩니다.',
        audience: '연구실책임자 · 시약 관리 담당', timing: '시약장 정리 · 신규 입고 시',
        steps: ['성상별 분류 기준 확인', '유별에 맞는 시약장/구역 배치'],
        notice: '',
        actions: [{ key: 'reagent-fireclass', label: '위험물유별로 시약 보기' }],
      },
    ],
  },

  special: {
    label: '특별관리물질',
    sections: [
      {
        key: 'targets', label: '대상물질', title: '특별관리물질 대상',
        summary: '현재 연구실이 보유한 시약을 특별관리물질 공식 목록과 CAS 기준으로 대조해 대상 물질을 보여줍니다.',
        audience: '연구실책임자 · 시약 관리 담당', timing: '신규 입고 시 · 정기 점검 시',
        roles: ['manager', 'director'],
        steps: ['현재 대상 물질 확인', '공식 시스템에서 등록', '취급 시 관련 기록 작성', '게시표지 확인'],
        notice: '대상 수는 DB의 CAS 매칭으로 실시간 계산합니다. 혼합물·농도 조건 등 CAS만으로 확정하기 어려운 항목은 "❓ 확인 필요"로 표시됩니다.',
        embed: 'specialTargets',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'register', label: '등록 준비', title: '특별관리물질 등록 준비',
        summary: `공식 등록은 ${SYS}에서 수행합니다. 앱에서는 등록에 필요한 시약 정보를 모아 보여주고 목록으로 내보냅니다.`,
        audience: '연구실책임자 · 연구실안전관리담당자', timing: '신규 특별관리물질 확인 시',
        roles: ['manager', 'director'],
        steps: ['현재 특별관리물질 보기', '등록에 필요한 정보 확인', '목록 내보내기(작성 참고용)', '학교 시스템에서 등록'],
        notice: '앱에서 "등록 완료" 상태를 만들지 않습니다. 내보내는 Excel은 작성 참고용입니다.',
        embed: 'specialRegister',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'handling', label: '취급관리', title: '특별관리물질 취급 관리',
        summary: '특별관리물질 취급 근로자의 작업환경관리 지침에 따른 취급 시 준수사항 안내입니다.',
        audience: '특별관리물질 취급자', timing: '취급 작업 전·중·후',
        steps: ['취급 전 보호구·환기 확인', '취급 중 노출 최소화', '취급 후 기록 작성'],
        notice: '',
        actions: [],
      },
      {
        key: 'log', label: '취급일지', title: '특별관리물질 취급일지 작성용 정보',
        summary: '공식 취급일지는 학교 양식/시스템에서 작성합니다. 앱은 시약 DB에서 자동으로 채울 수 있는 항목만 모아 제공합니다.',
        audience: '특별관리물질 취급자', timing: '취급일지 작성 시',
        roles: ['worker', 'manager'],
        steps: [
          '대상 물질(아래 목록) 확인',
          '자동 제공 정보(물질명·CAS·현재 잔량·입고일·보관 위치·Lot) 확인',
          '취급일자·실제 취급량·작업내용·착용 보호구·취급자·확인자·사고 조치사항은 공식 양식에 직접 작성',
        ],
        notice: '이 화면은 "작성용 정보"만 제공합니다. 취급일자·실제 취급량·작업내용·착용 보호구·취급자·확인자·사고 조치사항은 실제 작업별 기록이므로 공식 양식/시스템에서 작성하세요.',
        embed: 'specialLogInfo',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'sign', label: '게시표지', title: '특별관리물질 게시표지',
        summary: '취급 장소에 게시하는 공식 표지 자료를 제공합니다.',
        audience: '연구실책임자', timing: '특별관리물질 취급 장소 지정 시',
        steps: ['현재 보유 특별관리물질 확인', '게시용 표지 파일 열기', '취급 장소·출입구에 게시'],
        notice: '앱 안에서 별도의 표지 데이터베이스를 만들지 않습니다.',
        actions: [{ key: 'special-list', label: '현재 보유 특별관리물질' }],
      },
    ],
  },

  prior: {
    label: '사전유해인자',
    sections: [
      {
        key: 'flow', label: '전체 절차', title: '사전유해인자위험분석 전체 절차',
        summary: '사전준비 → 연구실 안전현황 → 연구개발활동별 유해인자 위험분석 → R&DSA → 승인 및 보고서 관리 순으로 진행합니다.',
        audience: '연구실책임자 · 연구책임자', timing: '연구 개시 전 · 연구내용 변경 시',
        steps: ['사전준비', '연구실 안전현황 작성', '연구개발활동별 유해인자 위험분석', 'R&DSA 작성', '승인 및 보고서 관리'],
        notice: '앱은 보고서를 대신 작성·제출하지 않습니다. 작성에 필요한 시약·유해인자 정보를 제공합니다.',
        actions: [],
      },
      {
        key: 'status', label: '안전현황', title: '연구실 안전현황',
        summary: `연구실정보·종사자·주요기자재·개인보호구·설비·배치도 등은 ${SYS}에서 관리합니다. 앱은 이 중 시약 관련 데이터만 지원합니다.`,
        audience: '연구실책임자', timing: '안전현황 작성·갱신 시',
        steps: ['현재 보유 시약 확인', '유해·위험 시약 / 위험물 현황 확인', '시약 목록 내보내기', '학교 시스템에 입력'],
        notice: '',
        actions: [
          { key: 'reagent-all', label: '현재 보유 시약' },
          { key: 'reagent-hazard', label: '유해·위험 시약' },
          { key: 'reagent-fireclass', label: '위험물 현황' },
          { key: 'reagent-excel', label: '시약 목록 내보내기' },
        ],
      },
      {
        key: 'risk', label: '위험분석', title: '연구개발활동별 유해인자 위험분석',
        summary: '사용 예정 시약을 선택하면 위험분석 작성에 필요한 정보(CAS·GHS·유해위험정보·보관 위치·규격·보유량·MSDS)를 빠르게 확인합니다.',
        audience: '연구책임자 · 연구활동종사자', timing: '위험분석 작성 시',
        steps: ['사용 예정 시약 선택', '유해·위험 정보 및 MSDS 확인', '위험분석 양식에 반영'],
        notice: '앱이 위험분석 결과나 위험등급을 최종 판정하지 않습니다.',
        actions: [{ key: 'reagent-lookup', label: '시약 정보 조회' }],
      },
      {
        key: 'rndsa', label: 'R&DSA', title: 'R&DSA',
        summary: '앱에서 R&DSA 편집기를 만들지 않습니다. 작성에 참고할 시약 정보·MSDS·가이드만 제공합니다.',
        audience: '연구책임자', timing: 'R&DSA 작성 시',
        steps: ['관련 시약 정보 확인', 'MSDS 확인', '작성가이드·예시집 참고', '학교 시스템에서 작성'],
        notice: '',
        actions: [
          { key: 'reagent-lookup', label: '관련 시약 정보' },
          { key: 'msds', label: 'MSDS 보기' },
          { key: 'school', label: '학교 시스템 열기' },
        ],
      },
      {
        key: 'ledger', label: '관리대장', title: '사전유해인자위험분석 보고서 관리대장',
        summary: '"사전유해인자위험분석 보고서 관리대장"과 "유해인자 취급·관리대장"은 서로 다른 문서입니다. 각 자료의 공식 명칭을 그대로 사용합니다.',
        audience: '연구실책임자', timing: '보고서 승인·보관 시',
        steps: ['보고서 관리대장 서식 확인', '승인된 보고서 이력 관리'],
        notice: '',
        actions: [],
      },
      {
        key: 'prepare', label: '작성 준비', title: '사전유해인자 작성 준비',
        summary: '연구실의 유해·위험 시약, 특별관리물질, 위험물을 필터로 걸러 작성 참고용 목록을 만들고 Excel로 내보냅니다. 보고서 자체는 학교 시스템에서 작성합니다.',
        audience: '연구책임자 · 연구실안전관리담당자', timing: '보고서 작성 준비 단계',
        roles: ['manager', 'director'],
        steps: ['필터(전체 / 유해·위험 / 특별관리물질 / 위험물) 선택', '작성 참고용 목록 확인', '작성 참고용 Excel 내보내기', '학교 시스템에서 보고서 작성'],
        notice: '이 Excel은 "작성 참고용"입니다. 학교 공식 업로드 양식이 아니며, 앱은 안전현황·위험분석·사전유해인자위험분석 보고서를 자체 생성하지 않습니다.',
        embed: 'priorPrepare',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
    ],
  },

  signage: {
    label: '안전표지·보호구',
    sections: [
      {
        key: 'small-container', label: '소분용기', title: '소분용기 경고표지',
        summary: '시약을 소분한 용기에는 물질·MSDS·GHS를 확인해 경고표지를 부착합니다. 경고표지는 KOSHA MSDS의 공식 경고표지 작성 기능으로 만듭니다(앱이 자체 생성하지 않음).',
        audience: '시약을 소분해 사용하는 연구활동종사자', timing: '소분 시마다 · 표지 훼손 시',
        roles: ['worker'],
        steps: ['물질 확인', 'MSDS/GHS 확인', '경고표지 작성 (KOSHA MSDS 공식 기능)', '용기에 맞는 크기 선택', '잘 보이는 곳에 부착 · 훼손 시 즉시 교체'],
        notice: '앱은 용기 크기에 따라 경고표지 PDF/이미지를 생성하지 않습니다. 공식 경고표지 작성 기능과 강원대학교 제공 작성방법 자료를 사용하세요.',
        actions: [
          { key: 'reagent-search', label: '시약 검색' },
          { key: 'msds', label: 'MSDS 보기' },
          { key: 'ghs', label: 'GHS 보기' },
          { key: 'kosha', label: '공식 경고표지 작성 사이트 열기' },
        ],
      },
      {
        key: 'ghs', label: 'GHS·경고표지', title: 'GHS 그림문자·경고표지',
        summary: '경고표지의 GHS 그림문자와 유해·위험문구는 해당 제품의 MSDS를 기준으로 확인합니다.',
        audience: '경고표지를 만드는 연구활동종사자', timing: '표지 작성 시',
        roles: ['worker'],
        steps: ['해당 제품 MSDS 확인', 'GHS 그림문자·H문구 확인', 'KOSHA MSDS 공식 경고표지 작성 기능으로 작성'],
        notice: '앱이 공급업체 MSDS를 대체하지 않습니다.',
        actions: [
          { key: 'reagent-search', label: '시약 검색' },
          { key: 'msds', label: 'MSDS' },
          { key: 'ghs', label: 'GHS 정보' },
          { key: 'kosha', label: '공식 경고표지 작성 사이트 열기' },
        ],
      },
      {
        key: 'safety-sign', label: '안전보건표지', title: '안전보건표지',
        summary: `공식 안전표지 관리는 ${SYS}에서 수행합니다. 앱은 표지 종류 안내와 관련 자료만 제공합니다.`,
        audience: '연구실책임자', timing: '출입구·취급 장소 표지 점검 시',
        steps: ['필요한 표지 종류 확인', '관련 자료 확인', '학교 시스템에서 표지 관리'],
        notice: '학교 시스템의 공식 안전표지 관리 기능을 복제하지 않습니다.',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'ppe', label: '보호구', title: '보호구',
        summary: '보호구 기본 안내와 특별관리물질 취급 시 보호구 안내, 관련 공식 자료를 제공합니다.',
        audience: '연구활동종사자', timing: '실험 준비 시 · 특별관리물질 취급 시',
        steps: ['작업에 맞는 보호구 확인', '특별관리물질 취급 시 추가 보호구 확인', '착용 후 실험'],
        notice: '별도의 보호구 재고관리는 만들지 않습니다.',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
    ],
  },

  ops: {
    label: '연구실 운영',
    sections: [
      {
        key: 'chem-register', label: '화학물질 등록', title: '학교 화학물질 등록',
        summary: '최근 입고 시약을 학교 화학물질 DB와 CAS로 대조해 등록 대상을 고르고, 학교 등록용 Excel을 만듭니다. 공식 등록은 학교 시스템에서 합니다.',
        audience: '연구실책임자 · 연구실안전관리담당자', timing: '신규 입고 후 · 정기 등록 시',
        roles: ['manager', 'director'],
        steps: ['최근 입고 시약 조회 (7일/30일/90일/1년)', '학교 화학물질 DB CAS 매칭 (✓매칭 / ⚠확인 필요)', '등록 대상 선택', '학교 등록용 Excel 생성', '학교 시스템에서 등록'],
        notice: '⚠ 미매칭 행은 CAS·명칭을 재확인한 뒤 포함 여부를 선택하세요.',
        embed: 'schoolRegistration',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'daily-check', label: '일상점검', title: '연구실 일상점검',
        summary: '연구활동 시작 전 연구실 안전상태를 확인합니다. 실제 점검 등록은 학교 공식 시스템에서 합니다.',
        audience: '연구활동종사자 · 연구실책임자', timing: '연구활동 시작 전(매일)',
        steps: ['일상점검 핵심 항목 확인', '학교 시스템에서 점검 등록', '연구실책임자 확인'],
        notice: '앱에 별도의 일상점검 기록 DB를 만들지 않습니다.',
        actions: [{ key: 'school', label: '학교 시스템에서 점검하기' }],
      },
      {
        key: 'incident', label: '사고대응', title: '사고 대응',
        summary: '사고 발생 시 본인 안전 확보 → 주변 알림 → 초기 대응 → 필요 시 119 → 연구실책임자 보고 → 학교 사고보고 절차.',
        audience: '모든 연구활동종사자', timing: '사고 발생 즉시',
        steps: ['본인 안전 확보', '주변에 사고 알림', '가능한 범위에서 초기 대응', '필요 시 119 신고', '연구실책임자 보고', '학교 사고보고 절차 진행'],
        notice: '',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'rules', label: '안전수칙', title: '연구실 안전수칙',
        summary: '실험 전·중·후 행동 수칙입니다. 실제 문구는 등록된 공식 자료를 기준으로 합니다.',
        audience: '모든 연구활동종사자', timing: '항상',
        steps: ['실험 전: 위험성 확인 · 보호구 착용 · 비상장비 위치 확인', '실험 중: 라벨 없는 용기 사용 금지 · 임의 혼합 금지 · 음식물 섭취 금지', '실험 후: 시약 원위치 · 폐기물 분리 · 작업대 정리'],
        notice: '',
        actions: [],
      },
      {
        key: 'edu', label: '안전교육', title: '안전교육',
        summary: '안전교육 이수 상태는 학교 공식 시스템에서 관리합니다. 앱은 교육 가이드와 링크만 제공합니다.',
        audience: '모든 연구활동종사자', timing: '학기 초 · 신규 채용 시',
        steps: ['안전교육 가이드 확인', '학교 시스템에서 교육 이수'],
        notice: '앱 자체에서 공식 교육이수 상태를 관리하지 않습니다.',
        actions: [{ key: 'school', label: '학교 시스템 열기' }],
      },
      {
        key: 'regulation', label: '안전관리규정', title: '연구실 안전관리규정',
        summary: '현재 규정 파일을 제공합니다. 상단에는 종사자에게 중요한 주요 의무만 요약합니다.',
        audience: '모든 연구활동종사자', timing: '규정 개정 시 · 안전교육 시',
        steps: ['안전교육 이수', '연구활동 전 일상점검', '개인보호구 착용', '안전수칙 준수', '사고 발생 시 즉시 조치·보고'],
        notice: '전체 규정 원문은 하단 자료에서 확인합니다.',
        actions: [],
      },
      {
        key: 'roles', label: '종사자·책임자', title: '연구활동종사자 · 연구실책임자',
        summary: '역할별 주요 업무 안내입니다.',
        audience: '연구활동종사자 / 연구실책임자', timing: '항상',
        steps: ['연구활동종사자: 일상점검 · 안전교육 · 보호구 착용 · 사고 보고 · 안전수칙 준수', '연구실책임자: 종사자 관리 · 점검 결과 확인 · 유해인자 관리 · 사전유해인자 · 안전자료·표지 관리 · 사고대응 관리'],
        notice: '',
        actions: [],
      },
    ],
  },
}
