-- STAGING TEST ONLY
-- NEVER APPLY TO PRODUCTION
-- NOT A PRODUCTION MIGRATION
drop function if exists public.admin_lot_move(uuid, uuid, text);
drop function if exists public.admin_lot_set_status(uuid, text);
drop function if exists public.admin_lot_update(uuid, jsonb);
drop function if exists public.reagent_enrich(uuid, jsonb);
drop function if exists public.reagent_confirm(text, uuid);
drop function if exists public.lot_add(text, uuid, jsonb);
drop function if exists public.reagent_register(text, text, uuid, jsonb, jsonb);
drop function if exists public._resolve_lot_no(jsonb);
drop function if exists public.admin_next_internal_lot_nos(int);
drop function if exists public._next_internal_lot_nos(int);
drop index if exists public.reagent_lots_generated_lot_no_key;
drop table if exists public.internal_lot_counters;
drop function if exists public.inventory_session_finalize(bigint);
drop function if exists public.inventory_session_transition(bigint, text);
drop function if exists public.inventory_session_start(int, date, text, text, text[], uuid[]);
drop function if exists public.inventory_new_registration(text, bigint, uuid, jsonb, jsonb, text);
drop function if exists public.inventory_count_save(text, bigint, jsonb);
drop function if exists public._inventory_open_session_check(bigint, text);
drop table if exists inventory_assignments;
drop table if exists inventory_counts;
drop table if exists inventory_sessions;
drop function if exists public.purchase_request_log_update(uuid, text, text, text, text);
drop function if exists public.purchase_request_submit(text, jsonb, jsonb);
drop function if exists public.notice_increment_views(uuid);
drop table if exists purchase_request_goods_items;
drop table if exists purchase_request_reagent_items;
drop table if exists purchase_request_logs;
drop function if exists public.admin_dispose_lots(uuid[], text);
drop function if exists public.admin_move_lots(uuid[], uuid);
drop function if exists public.disposal_request_review(uuid, text, text);
drop function if exists public.location_request_review(uuid, text, text);
drop function if exists public.reagent_change_request_review(uuid, text, text);
drop function if exists public._location_label(uuid, text);
drop function if exists public._admin_actor();
drop function if exists public.location_request_submit(text, uuid, uuid, text, uuid, text, uuid, text, text);
drop function if exists public.reagent_change_request_submit(text, uuid, text, text, text);
drop table if exists location_requests;
drop table if exists reagent_change_requests;
drop function if exists public.disposal_request_submit(text, uuid, uuid, text, text, text, text);
drop table if exists disposal_requests;
drop function if exists public.student_logout(text);
drop function if exists public.student_session_refresh(text);
drop function if exists public._resolve_student_session(text);
drop function if exists public._issue_student_session(text);
drop table if exists student_sessions;
drop function if exists public.admin_password_change(text, text);
drop function if exists public.student_admin_upgrade(text, text);
drop function if exists public.student_register(text, text, date);
drop function if exists public.student_admin_login(text, text, date, text);
drop function if exists public.student_check_login(text, text, date);
drop table if exists app_settings;
drop table if exists students;
