-- STAGING TEST ONLY
-- NEVER APPLY TO PRODUCTION
-- NOT A PRODUCTION MIGRATION
--
-- Master Finish Phase 2 — 20260920120000_inventory_workflow.sql 검증용 fixture.
-- production 실제 컬럼/제약(inventory_counts UNIQUE(session_id, lot_id), bigint id 등)을 재현한다.
-- acl-fixture-schema.sql 보다 먼저 실행해야 한다(그쪽 generic 테이블이 이 실제 테이블을 대체하지 않도록).
alter table reagents add column if not exists pending_confirm boolean not null default false;
alter table reagents add column if not exists registered_by text;
alter table reagents add column if not exists sort_letter text;
alter table reagent_lots add column if not exists pending_confirm boolean not null default false;

create table if not exists inventory_sessions (
  id bigint generated by default as identity primary key,
  year int not null,
  start_date date not null,
  status text default 'active',
  created_by text not null,
  completed_at timestamptz,
  created_at timestamptz default now(),
  paused_at timestamptz,
  paused_by text,
  label text,
  purpose text not null default 'current_list' check (purpose in ('full_census', 'current_list')),
  zones text[]
);
create table if not exists inventory_counts (
  id bigint generated by default as identity primary key,
  session_id bigint references inventory_sessions(id),
  reagent_id uuid references reagents(id),
  lot_id uuid references reagent_lots(id),
  book_sealed int, book_stock int,
  actual_sealed int, actual_stock int,
  counted_by text, counted_at timestamptz,
  is_locked boolean default false, lock_by text,
  created_at timestamptz default now(),
  counted_by_student_id text,
  reported_missing boolean not null default false,
  abnormal_note text,
  is_new_registration boolean not null default false,
  staged_location_id uuid references locations(id),
  book_status text,
  book_location_id uuid references locations(id),
  staged_reagent_fields jsonb, book_reagent_fields jsonb,
  staged_lot_fields jsonb, book_lot_fields jsonb,
  unique (session_id, lot_id)
);
create table if not exists inventory_assignments (
  id bigint generated by default as identity primary key,
  session_id bigint references inventory_sessions(id),
  zone text, assigned_to text, status text default 'pending',
  created_at timestamptz default now(), completed_at timestamptz, assigned_student_id text
);
drop table if exists stock_logs;
create table stock_logs (
  id uuid primary key default gen_random_uuid(),
  target_type text check (target_type in ('reagent', 'item')),
  lot_id uuid, user_name text,
  before_sealed int, after_sealed int, before_stock int, after_stock int,
  notes text, changed_at timestamptz default now(), created_at timestamptz default now()
);
