import { browserLaunch, session, waitList, BASE } from './lib.mjs'
const browser = await browserLaunch(false)
const { ctx, page } = await session(browser, { w: 1440, h: 900 })
await page.goto(BASE + '/reagents/list', { waitUntil: 'domcontentloaded' }); await waitList(page)
await page.evaluate(() => window.scrollTo(0, 2200)); await page.waitForTimeout(800)
const y0 = await page.evaluate(() => window.scrollY)
await page.locator('tbody tr[title^="클릭"]').nth(4).locator('td').nth(1).click()
await page.waitForURL(/\/reagents\/[0-9a-f-]{36}/); await page.waitForTimeout(500)
const snap = await page.evaluate(() => sessionStorage.getItem('reagentList:view:v1'))
console.log('snapshot at leave:', snap && snap.slice(0, 260), 'y0', y0)
await page.evaluate(() => { window.__log = []; const t0 = performance.now(); const tick = () => { window.__log.push([Math.round(performance.now() - t0), Math.round(scrollY), document.documentElement.scrollHeight, document.querySelectorAll('[data-index]').length]); if (performance.now() - t0 < 4000) setTimeout(tick, 100) }; window.__t = tick })
await page.getByRole('button', { name: '시약 목록으로 돌아가기' }).click()
await page.evaluate(() => window.__t && window.__t())
await page.waitForTimeout(4500)
const log = await page.evaluate(() => window.__log || null)
console.log('timeline [ms, scrollY, docHeight, rows]:', JSON.stringify(log && log.filter((_, i) => i % 3 === 0)))
console.log('history.scrollRestoration =', await page.evaluate(() => history.scrollRestoration))
await browser.close()
